name: Update Version Tag

on:
  workflow_dispatch:
  push:
    branches: [ 'renovate/ghcr.io-actions-actions-runner-*' ]

permissions:
  contents: write

jobs:
  puah-tag:
    name: Push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Get actions-runner version
        run: |
          version=$(awk '/^FROM/ {print $2}' Dockerfile | cut -d':' -f2)
          echo "RUNNER_VERSION=$version"  >> $GITHUB_ENV
          echo "TAG=v$version"  >> $GITHUB_ENV

      - name: Add version tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          echo "https://${{ github.actor }}:${{ github.token }}@github.com" > ~/.netrcgit-credentials
          current_version=$(git describe --tags --always)
          if [[ "$current_version" == *"v$RUNNER_VERSION"* ]]; then
              echo "Tag already exists"
          else
            git tag -a $TAG -m "Actions runner version $RUNNER_VERSION"
            git push origin $TAG
          fi
